### ISSUE TITLE
Publish/post article to another sections

### ISSUE THREAD

**Issue by mohdakl** [sketchytech/AppleNewsFormat#1]
In my apple news publisher i have 3 sections and the python code and article.json publishing the the article only to the main (default) section.

**Comment by sketchytech** [comment]
You need to obtain the ID for the section you wish to post to (see [List Sections](https://developer.apple.com/library/content/documentation/General/Conceptual/News_API_Ref/ListSections.html#//apple_ref/doc/uid/TP40015409-CH11-SW1)).

Next you need to upload with [metadata](https://developer.apple.com/library/content/documentation/General/Conceptual/News_API_Ref/CreateArticle.html#//apple_ref/doc/uid/TP40015409-CH14-SW11) where inside the "links" dictionary you have a "sections" key with an array of section urls listing the sections within which the article should be contained.

**Comment by mohdakl** [comment]
Thanks @sketchytech 
is this can be added in article.json ? 

Can you please post an example of adding this ?

**Comment by sketchytech** [comment]
No it can't be added to `article.json` the metadata within the article is different to the metadata of the POST request. You need to construct a multipart POST request that features the metadata as shown in [the docs](https://developer.apple.com/library/content/documentation/General/Conceptual/News_API_Ref/CreateArticle.html#//apple_ref/doc/uid/TP40015409-CH14-SW11).

Sorry, I don't have time at the moment to write out the code for this and it's beyond the scope of this repository, the aim of which is to provide the json structures for the contents of Apple News articles.
